model:
  bert_model_name : 'bert-base-uncased'
  lr : 2e-5
  batch_size : 32
  data_root : "./data/processed/"
  num_workers : 8
  use_short_data : 1000 # None if we should use the whole data

train:
  num_epochs : 3
  print_every : 7
  seed : 42
  device : "auto" # set to "auto" for automatic selection, "gpu" to force gpu, "cpu" to force cpu

predict:
  checkpoint_path: models/bert-toxic-classifier/epoch=1-val_loss=0.15.ckpt
  
# In config_train.yaml
hydra:
  run:
    dir: outputs/hydra/hydra_${now:%Y-%m-%d}_${now:%H-%M-%S}
  output_subdir: null
