model:
  bert_model_name : 'bert-base-uncased'
  lr : 2e-5
  batch_size : 10
  data_root : "./data/processed/"
  num_workers : 4
  use_short_data : null # None if we should use the whole data

train:
  num_epochs : 1
  print_every : 7
  seed : 42
  device : "auto" # set to gpu if you want to use any gpu

predict:
  checkpoint_path: models/bert_toxic_classifier_logs/version_16/checkpoints/epoch=0-step=125.ckpt

# In config_train.yaml
hydra:
  run:
    dir: outputs/hydra/hydra_${now:%Y-%m-%d}_${now:%H-%M-%S}
  output_subdir: null
