model:
  bert_model_name : 'bert-base-uncased'
  lr : 2e-5
  batch_size : 10
  data_root : "./data/processed/"
  num_workers : 4
  use_short_data : null # None if we should use the whole data

train:
  num_epochs : 1
  print_every : 7
  seed : 42
  device : "cpu" # set to "auto" for automatic selection, "gpu" to force gpu, "cpu" to force cpu

predict:
  checkpoint_path: models/production/production.ckpt


  

# In config_train.yaml
hydra:
  run:
    dir: outputs/hydra/hydra_${now:%Y-%m-%d}_${now:%H-%M-%S}
  output_subdir: null
