steps:
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['cp', 'gs://group_60_models/production/production.ckpt', '/workspace/models/production/production.ckpt']

# Add this debugging step to list the contents of /workspace/models/production
- name: 'ubuntu'
  args: ['bash', '-c', 'ls -l /workspace/models/']

# Add this debugging step to list the contents of /workspace
- name: 'ubuntu'
  args: ['bash', '-c', 'ls -l /workspace']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-f', './dockerfiles/inference_streamlit.dockerfile', '-t', 'gcr.io/$PROJECT_ID/inference-streamlit', '/workspace']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/inference-streamlit']