hyperparameters:
  batch_size : 8
  lr : 2e-5
  num_epochs : 1
  print_every : 7
  bert_model_name : 'bert-base-uncased'
  num_workers : 3
  use_short_data : 100 #1000 # None if we should use the whole data
  seed : 42
  device : "cpu" # set to gpu if you want to use any gpu
checkpoint_path: models/bert_toxic_classifier_logs/version_16/checkpoints/epoch=0-step=125.ckpt
