name: "Run codechecks"

on:
  pull_request:
    branches: [ master, main ]
  push:
    branches: [63-add-multisystem-testing]


jobs:
  Codecheck:

    runs-on: ${{ matrix.os }}
    strategy:
     matrix:
       os: [ubuntu-latest, macos-latest]

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Python 3.11.5
      uses: actions/setup-python@v5
      with:
        python-version: 3.11.5
        cache: 'pip' # caching pip dependencies

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt

    - name: Run ruff check
      run: |
        ruff check

    - name: Run ruff format
      run: |
        ruff format

    - name: Auto commit format changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Changes from ruff autoformatting
