name: "Run codeTest"

on:
  push:
    branches: [ CI ]

jobs:
  Codecheck:

    runs-on: [ubuntu-latest]
    #permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      #contents: write
    steps:

    - name: Test with pytest
      run: |
          python -m pip install dvc 
          python -m pip install dvc-gs
          python -m pip install --upgrade pyOpenSSL
          dvc init --no-scm
          dvc remote add gcloud-storage gs://group_60_data/
          dvc remote default gcloud-storage
          dvc pull --run-cache
          pip install -r requirements_tests.txt
          pytest tests/test_model.py 
