name: "Run codeTest"

on:
  push:
    branches: [ CI ]

jobs:
  Codecheck:

    runs-on: [ubuntu-latest]
    #permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      #contents: write
    steps:

    - name: Test with pytest
      run: |
          python -m pip install dvc 
          python -m pip install dvc-gdrive
          dvc init --no-scm
          dvc remote add -d storage gdrive://1hTJ0wghBp-5BabYJq3Cg9kUj2rdoEhIe
          dvc pull --run-cache
          pip install -r requirements_tests.txt
          pytest tests/test_model.py 
